name: "DeepL Translator (EN→DE)"
slug: "deepl-en-de"
base_url: "https://www.deepl.com"
description: "Translate text from English to German using DeepL"
capabilities:
  - search
endpoints:
  search:
    url: "https://www.deepl.com/en/translator#en/de/"
    actions:
      - type: wait
        selector: "d-textarea"
        timeout: 10000
    items:
      container: "d-textarea"
      fields:
        text:
          selector: ""
          attribute: "text"
    pagination:
      type: "page_param"
      param: "p"
      start: 1
